name: MATLAB Jupyter Integration

on:
  push:
    branches:
      - "main"

jobs:
  node_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 13.x
        uses: actions/setup-node@v2
        with:
          node-version: 13.x

      - name: Install Node dependencies
        run: npm --prefix gui install gui

      - name: Build Project
        run: npm --prefix gui build --if-present

      - name: Run Node tests
        run: npm --prefix gui test

  python_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pytest

      - name: Lint with black
        run: |
          black --check .

      - name: Test with pytest
        run: |
          python setup.py test

  generate_and_upload_code_coverage:
    needs: [python_tests, node_tests]
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Use Node.js 13.x
        uses: actions/setup-node@v2
        with:
          node-version: 13.x

      - name: Install Python build dependencies
        run: |
          pip install -e .[DEV]

      - name: Generate Code Coverage report for Python code
        run: |
          pytest --cov=./ --cov-report=xml

      - name: Upload python coverage report to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: ./
          name: Python-codecov
          files: ./coverage.xml
          fail_ci_if_error: true
          verbose: true

      - name: Install Node Dependencies
        run: npm --prefix gui install gui

      - name: Generate code coverage for Javascript code
        run: npm --prefix gui test -- --coverage --watchAll=false

      - name: Upload Javscript coverage report to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: ./gui/coverage/
          fail_ci_if_error: true
          verbose: true
